version: "3"
services:
  proxy:
    # container_name: "proxy"
    build: ./proxy
    # image: nginx:alpine
    # volumes:
    #   - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    # links:
    #   - "backend"
    # stdin_open: true
    # tty: true

  backend:
    container_name: "backend"
    build: ./backend
    ports:
      - "50051:50051"
    volumes:
      - ./backend:/usr/src/app
